drop table if exists uzytkownicy cascade;
drop table if exists obserwujacy cascade;
drop table if exists playlisty cascade;
drop table if exists gatunki cascade;
drop table if exists albumy cascade;
drop table if exists utwory cascade;
drop table if exists utwory_playlisty cascade;
drop table if exists autorzy cascade;
drop table if exists utwory_autorzy cascade;
drop table if exists autorzy_zespoly cascade;
drop table if exists autorzy_zespoly_role cascade;
drop table if exists utwory_autorzy_role cascade;
drop table if exists role cascade;
drop table if exists oceny cascade;
drop function if exists add_rating;
drop function if exists album_autorzy;
drop function if exists autor_role;
drop function if exists autorzy;
drop function if exists correct_author_band;
drop function if exists dodaj_numer_w_playliscie;
drop function if exists ocena;
drop function if exists rekomendacje;
drop function if exists remove_rating;
drop function if exists widoczne_playlisty;
drop function if exists widoczne_playlisty_tworcy;
drop function if exists wypisz_role_autora;
drop function if exists zero_ratings;